#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
smoke_script="${repo_root}/scripts/kvm-smoke-headless.sh"

usage() {
  cat <<'EOF'
Create a persistent Fedora KVM playground VM with the packaged Hyprland stack.

This script builds on `scripts/kvm-smoke-headless.sh`:
1. Boots and validates a graphical Hyprland VM (GDM path) using the existing
   KVM smoke harness.
2. Keeps the VM running.
3. Converts it into a manual-playground VM by disabling GDM autologin,
   setting a password for the Fedora user, and ensuring the full package set
   (including `waybar`) plus a small workstation app bundle is installed.

Usage:
  scripts/kvm-playground-vm.sh [options]

Options:
  --user-password PASSWORD   Password to set for the Fedora user (default:
                             auto-generate a random password and print it)
  --session NAME             Default GDM session for the Fedora user
                             (default: hyprland; alt: hyprland-uwsm)
  --ssh-user USER            Guest user name (default: fedora)
  --keep-smoke-log           Keep the temporary wrapper launch log under /tmp
  --help                     Show this help

All other options are passed through to `scripts/kvm-smoke-headless.sh`, with
these enforced defaults:
  --smoke-mode graphical
  --graphical-session-mode gdm
  --keep-vm

Recommended examples:
  ./scripts/kvm-playground-vm.sh --release 43 --graphics-accel off

  ./scripts/kvm-playground-vm.sh \
    --release 44 --memory-mib 8192 --vcpus 6 --graphics-accel off

Notes:
  - The VM initially boots through the smoke harness and typically ends inside
    a logged-in Hyprland session. This script disables GDM autologin for the
    next login, so logout returns to the GDM greeter for manual login/logout.
  - Password SSH login is enabled in the guest for convenience, in addition to
    the SSH key generated by the smoke harness.
  - The script attempts to install Google Chrome from Google's RPM repo and
    falls back to Fedora `chromium` if that fails.
EOF
}

log() {
  printf '[kvm-playground] %s\n' "$*"
}

die() {
  printf '[kvm-playground] ERROR: %s\n' "$*" >&2
  exit 1
}

generate_password() {
  local length="${1:-20}"
  local out=""

  while ((${#out} < length)); do
    out+="$(
      LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c "$((length - ${#out}))" || true
    )"
  done

  printf '%s\n' "${out}"
}

ssh_opts() {
  local key_path="$1"
  printf '%s\n' \
    "-i" "$key_path" \
    "-o" "BatchMode=yes" \
    "-o" "IdentitiesOnly=yes" \
    "-o" "PreferredAuthentications=publickey" \
    "-o" "PasswordAuthentication=no" \
    "-o" "StrictHostKeyChecking=no" \
    "-o" "UserKnownHostsFile=/dev/null" \
    "-o" "ConnectTimeout=10"
}

extract_kvm_smoke_value() {
  local key="$1"
  local log_file="$2"
  sed -n "s/^\\[kvm-smoke\\] ${key}: //p" "${log_file}" | tail -n 1
}

wait_for_ssh_with_key() {
  local user="$1"
  local ip="$2"
  local key_path="$3"
  local -a opts
  local i

  mapfile -t opts < <(ssh_opts "${key_path}")

  for i in $(seq 1 30); do
    if ssh "${opts[@]}" "${user}@${ip}" 'true' >/dev/null 2>&1; then
      return 0
    fi
    sleep 2
  done

  return 1
}

main() {
  local user_password=""
  local session_name="hyprland"
  local ssh_user="fedora"
  local keep_wrapper_log=0
  local -a passthrough_args=()
  local smoke_log run_dir vm_name vm_ip libvirt_uri ssh_key
  local generated_password=0
  local password_b64 cred_file
  local -a opts

  [[ -x "${smoke_script}" ]] || die "Missing executable smoke harness: ${smoke_script}"

  while (($#)); do
    case "$1" in
      --user-password)
        user_password="${2:-}"
        [[ -n "${user_password}" ]] || die "--user-password requires a value"
        shift 2
        ;;
      --session)
        session_name="${2:-}"
        [[ -n "${session_name}" ]] || die "--session requires a value"
        shift 2
        ;;
      --ssh-user)
        ssh_user="${2:-}"
        [[ -n "${ssh_user}" ]] || die "--ssh-user requires a value"
        passthrough_args+=("$1" "$2")
        shift 2
        ;;
      --keep-smoke-log)
        keep_wrapper_log=1
        shift
        ;;
      --help)
        usage
        exit 0
        ;;
      --smoke-mode|--graphical-session-mode|--keep-vm)
        die "Do not pass ${1}; this script enforces graphical GDM smoke with --keep-vm"
        ;;
      *)
        passthrough_args+=("$1")
        if [[ $# -ge 2 ]]; then
          case "$1" in
            --owner|--project|--base-image|--release|--vm-name|--memory-mib|--vcpus|--disk-size-gb|--network|--connect|--graphics|--graphics-accel|--osinfo|--timeout-sec|--workdir)
              passthrough_args+=("$2")
              shift 2
              continue
              ;;
          esac
        fi
        shift
        ;;
    esac
  done

  case "${session_name}" in
    hyprland|hyprland-uwsm)
      ;;
    *)
      die "Unsupported --session value: ${session_name} (expected: hyprland or hyprland-uwsm)"
      ;;
  esac

  if [[ "${user_password}" == *$'\n'* ]]; then
    die "--user-password must not contain newlines"
  fi

  if [[ -z "${user_password}" ]]; then
    user_password="$(generate_password 20)"
    generated_password=1
  fi

  smoke_log="$(mktemp /tmp/kvm-playground-launch.XXXXXX.log)"
  log "Using smoke harness to provision and validate a graphical VM (log: ${smoke_log})"

  if ! "${smoke_script}" \
      --smoke-mode graphical \
      --graphical-session-mode gdm \
      --keep-vm \
      "${passthrough_args[@]}" \
      2>&1 | tee "${smoke_log}"; then
    die "Smoke harness failed (see ${smoke_log})"
  fi

  run_dir="$(extract_kvm_smoke_value "Run directory" "${smoke_log}")"
  vm_name="$(extract_kvm_smoke_value "VM name" "${smoke_log}")"
  vm_ip="$(extract_kvm_smoke_value "VM IP address" "${smoke_log}")"
  libvirt_uri="$(extract_kvm_smoke_value "Libvirt URI" "${smoke_log}")"

  [[ -n "${run_dir}" ]] || die "Could not parse run directory from smoke harness output"
  [[ -n "${vm_name}" ]] || die "Could not parse VM name from smoke harness output"
  [[ -n "${vm_ip}" ]] || die "Could not parse VM IP address from smoke harness output"
  [[ -n "${libvirt_uri}" ]] || libvirt_uri="qemu:///system"

  ssh_key="${run_dir}/id_ed25519"
  [[ -f "${ssh_key}" ]] || die "Missing SSH key from smoke run: ${ssh_key}"

  if ! wait_for_ssh_with_key "${ssh_user}" "${vm_ip}" "${ssh_key}"; then
    die "Timed out reconnecting to ${ssh_user}@${vm_ip} after smoke provisioning"
  fi

  password_b64="$(printf '%s' "${user_password}" | base64 | tr -d '\n')"
  mapfile -t opts < <(ssh_opts "${ssh_key}")

  log "Converting the smoke VM into a persistent playground (password login + no GDM autologin)"
  ssh "${opts[@]}" "${ssh_user}@${vm_ip}" \
    sudo bash -s -- "${ssh_user}" "${session_name}" "${password_b64}" \
    >"${run_dir}/playground-prepare.log" 2>&1 <<'EOF'
set -euo pipefail

login_user="$1"
session_name="$2"
password_b64="$3"
password="$(printf '%s' "${password_b64}" | base64 -d)"

# Ensure the full package set is present, including waybar (not yet covered by
# every smoke profile) and common workstation apps for manual experimentation.
dnf -y --refresh install --setopt=install_weak_deps=0 --nodocs \
  gdm \
  kitty \
  waybar \
  dolphin \
  nautilus \
  file-roller \
  pavucontrol \
  mako \
  xdg-utils \
  xdg-user-dirs \
  wl-clipboard \
  playerctl \
  brightnessctl \
  NetworkManager-applet \
  NetworkManager-wifi \
  NetworkManager-wifi-gnome \
  gvfs \
  gvfs-archive \
  gvfs-mtp \
  gvfs-smb \
  hyprwayland-scanner \
  hyprutils \
  hyprlang \
  hyprcursor \
  hyprgraphics \
  aquamarine \
  hyprwire \
  hyprland-protocols \
  glaze \
  hyprland \
  hyprland-uwsm \
  xdg-desktop-portal-hyprland \
  uwsm \
  hyprlock \
  hypridle \
  hyprpaper \
  hyprpicker \
  hyprsunset \
  hyprpolkitagent \
  hyprland-qt-support \
  hyprqt6engine \
  hyprland-guiutils \
  hyprsysteminfo \
  hyprlauncher \
  hyprshot \
  hyprpwcenter \
  hyprdim \
  hyprshutdown \
  hyprtoolkit \
  hyprland-plugins \
  hyprland-plugin-borders-plus-plus \
  hyprland-plugin-csgo-vulkan-fix \
  hyprland-plugin-hyprbars \
  hyprland-plugin-hyprexpo \
  hyprland-plugin-hyprfocus \
  hyprland-plugin-hyprscrolling \
  hyprland-plugin-hyprtrails \
  hyprland-plugin-hyprwinwrap \
  hyprland-plugin-xtra-dispatchers

# Try to provide a familiar proprietary browser in the playground VM. If the
# Google repo/package is unavailable for the Fedora release, fall back to
# Fedora's Chromium package without failing the whole playground setup.
cat > /etc/yum.repos.d/google-chrome.repo <<GOOGLECHROME
[google-chrome]
name=google-chrome
baseurl=https://dl.google.com/linux/chrome/rpm/stable/x86_64
enabled=1
gpgcheck=1
gpgkey=https://dl.google.com/linux/linux_signing_key.pub
repo_gpgcheck=0
skip_if_unavailable=True
GOOGLECHROME

if ! dnf -y --refresh install --setopt=install_weak_deps=0 --nodocs google-chrome-stable; then
  dnf -y --refresh install --setopt=install_weak_deps=0 --nodocs chromium || true
fi

echo "${login_user}:${password}" | chpasswd
passwd -u "${login_user}" >/dev/null 2>&1 || true
chage -I -1 -m 0 -M 99999 -E -1 "${login_user}" || true

mkdir -p /etc/gdm
cat > /etc/gdm/custom.conf <<GDMCONF
[daemon]
WaylandEnable=true
GDMCONF

mkdir -p /var/lib/AccountsService/users
cat > /var/lib/AccountsService/users/${login_user} <<ACCOUNTS
[User]
SystemAccount=false
Session=${session_name}
XSession=${session_name}
ACCOUNTS
chmod 0644 /var/lib/AccountsService/users/${login_user}

mkdir -p /etc/ssh/sshd_config.d
cat > /etc/ssh/sshd_config.d/90-kvm-playground-password-auth.conf <<SSHCONF
PasswordAuthentication yes
KbdInteractiveAuthentication yes
UsePAM yes
SSHCONF
chmod 0644 /etc/ssh/sshd_config.d/90-kvm-playground-password-auth.conf

systemctl enable gdm.service
systemctl set-default graphical.target
systemctl reload sshd || systemctl restart sshd || true
loginctl enable-linger "${login_user}" || true

touch /var/tmp/kvm-playground-ready
EOF

  cred_file="${run_dir}/playground-credentials.txt"
  umask 077
  {
    printf 'VM Name: %s\n' "${vm_name}"
    printf 'VM IP: %s\n' "${vm_ip}"
    printf 'Libvirt URI: %s\n' "${libvirt_uri}"
    printf 'User: %s\n' "${ssh_user}"
    printf 'Password: %s\n' "${user_password}"
    printf 'Default session: %s\n' "${session_name}"
    printf 'SSH key: %s\n' "${ssh_key}"
  } > "${cred_file}"

  if [[ "${keep_wrapper_log}" -eq 0 ]]; then
    rm -f "${smoke_log}"
    smoke_log="(removed; pass --keep-smoke-log to keep wrapper log)"
  fi

  log "Playground VM is ready."
  log "VM name: ${vm_name}"
  log "VM IP: ${vm_ip}"
  log "Libvirt URI: ${libvirt_uri}"
  log "Run directory: ${run_dir}"
  log "SSH key: ${ssh_key}"
  log "Credentials file (0600): ${cred_file}"

  if [[ "${generated_password}" -eq 1 ]]; then
    log "Generated password for ${ssh_user}: ${user_password}"
  else
    log "Configured password for ${ssh_user}: ${user_password}"
  fi

  cat <<EOF

Next steps:
1. Open the VM in virt-manager (or use virt-viewer) and continue using the
   current Hyprland session.
2. Log out once to reach GDM; autologin has been disabled.
3. Log back in as '${ssh_user}' with the password above (default session: ${session_name}).

Useful commands:
  ssh -i '${ssh_key}' ${ssh_user}@${vm_ip}
  ssh ${ssh_user}@${vm_ip}    # password login is enabled
  sudo virsh --connect ${libvirt_uri} domifaddr ${vm_name}
  sudo virsh --connect ${libvirt_uri} destroy ${vm_name}
  sudo virsh --connect ${libvirt_uri} undefine ${vm_name} --nvram

Artifacts:
  ${run_dir}
  ${run_dir}/playground-prepare.log
  ${cred_file}

EOF
}

main "$@"
