Name:           swappy
Version:        1.8.0
Release:        %autorelease
Summary:        Wayland-native snapshot editing tool inspired by Snappy

License:        MIT
URL:            https://github.com/jtheoof/swappy
Source0:        %{url}/releases/download/v%{version}/%{name}-%{version}.tar.gz

BuildRequires:  desktop-file-utils
BuildRequires:  gcc
BuildRequires:  gettext
BuildRequires:  meson
BuildRequires:  scdoc
BuildRequires:  pkgconfig(cairo)
BuildRequires:  pkgconfig(gio-2.0)
BuildRequires:  pkgconfig(gtk+-3.0)
BuildRequires:  pkgconfig(libnotify)
BuildRequires:  pkgconfig(pango)

Recommends:     fontawesome-6-free-fonts
Recommends:     wl-clipboard

%description
Swappy is a Wayland-native snapshot editor. It works well with grim and slurp,
but can also edit PNG data generated by other screen copy tools.

%prep
%autosetup -n %{name}-%{version}

%build
%meson
%meson_build

%install
%meson_install

%find_lang %{name}

%check
desktop-file-validate %{buildroot}%{_datadir}/applications/%{name}.desktop

%files -f %{name}.lang
%license LICENSE
%doc README.md
%doc example/config
%{_bindir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/scalable/apps/%{name}.svg
%{_mandir}/man1/%{name}.1.*

%changelog
%autochangelog
